# Generated by Django 5.0 on 2024-01-16 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('pk1', models.AutoField(primary_key=True, serialize=False)),
                ('big_number', models.BigIntegerField()),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('binary_data', models.BinaryField(blank=True, null=True)),
                ('isEmployee', models.BooleanField(blank=True, null=True)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('EventTime', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('num1', models.PositiveIntegerField(blank=True, null=True)),
                ('num2', models.PositiveBigIntegerField(blank=True, null=True)),
                ('num3', models.SmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('TermsAndCondition', models.BooleanField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('pk2', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('roll', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('subject', models.CharField(blank=True, max_length=40, null=True)),
                ('teacher_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Course')),
                ('credit', models.IntegerField(blank=True, null=True)),
                ('students', models.ManyToManyField(blank=True, null=True, related_name='courses', to='myApp.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Students', to='myApp.teacher'),
        ),
    ]
